services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5438:5432'
    volumes: 
      - ./sample-data-postgres.sql:/docker-entrypoint-initdb.d/sample-data.sql
      - ./sample-data.csv:/docker-entrypoint-initdb.d/sample-data.csv